apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
spec:
  selector:
    app: demo-api
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8000
      nodePort: 30000
